### Create a New Room✔️
POST http://localhost:5000/rooms/create-new-room
Content-Type: application/json

{
  "name": "New Room 1"
}

###

### Join a Room✔️
POST http://localhost:5000/rooms/123e4567-e89b-12d3-a456-426614174000/join/222e4567-e89b-12d3-a456-426614174222
Content-Type: application/json

###

### Get Next Scenario❌
GET http://localhost:5000/rooms/123e4567-e89b-12d3-a456-426614174000/next-scenario/111e4567-e89b-12d3-a456-426614174111

###

### Submit an Answer❌
POST http://localhost:5000/rooms/123e4567-e89b-12d3-a456-426614174000/answers
Content-Type: application/json

{
  "scenario_id": 1,
  "answer": true,
  "comment": "This is my answer",
  "user_id": "111e4567-e89b-12d3-a456-426614174111"
}

###

### Get Statistics❌
GET http://localhost:5000/rooms/123e4567-e89b-12d3-a456-426614174000/statistics/1

###

### Process a Scenario❌
POST http://localhost:5000/scenarios/process
Content-Type: application/json

{
  "text": "Rewrite this scenario using AI."
}

###

### Create a User❌
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "Charlie",
  "email": "charlie@example.com",
  "password": "securepassword3"
}

###

### Get All Users❌
GET http://localhost:5000/users

###

### Get a Single User ❌
GET http://localhost:5000/users/111e4567-e89b-12d3-a456-426614174111

###

### Delete a User
DELETE http://localhost:5000/users/111e4567-e89b-12d3-a456-426614174111
