### Create a New Room✔️
POST http://localhost:5000/rooms/create-new-room
Content-Type: application/json

{
    "roomId": "123e4567-e89b-12d3-a456-426614174000",
    "currentScenarioId": "63f1e1a2b4d6f123456789ab",
    "name": "Room 1",
    "ownerId": "111e4567-e89b-12d3-a456-426614174111"
}

###

### Join a Room✔️
POST http://localhost:5000/rooms/fc4d2dec-e754-435d-a635-540383dab6c1/join/05ed1b0c-db3d-43a9-bc7f-09a1a3e2e0fe
Content-Type: application/json

###

### Get Next Scenario✔️

###GET /rooms/{room_id}/next-scenario{owner_id}
GET http://localhost:5000/rooms/fc4d2dec-e754-435d-a635-540383dab6c1/next-scenario/5b302dc6-1a09-445d-ae01-d4b06c741b82

###

### Submit an Answer❌
POST http://localhost:5000/rooms/123e4567-e89b-12d3-a456-426614174000/answers
Content-Type: application/json

{
  "scenario_id": 1,
  "answer": true,
  "comment": "This is my answer",
  "user_id": "111e4567-e89b-12d3-a456-426614174111"
}

###

### Get Statistics❌
GET http://localhost:5000/rooms/123e4567-e89b-12d3-a456-426614174000/statistics/1

###

### Process a Scenario❌
POST http://localhost:5000/scenarios/process
Content-Type: application/json

{
  "text": "Rewrite this scenario using AI."
}

###

### Create a User❌
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "Charlie",
  "email": "charlie@example.com",
  "password": "securepassword3"
}

###

### Get All Users❌
GET http://localhost:5000/users

###

### Get a Single User ❌
GET http://localhost:5000/users/111e4567-e89b-12d3-a456-426614174111

###

### Delete a User
DELETE http://localhost:5000/users/111e4567-e89b-12d3-a456-426614174111
